### ISSUE TITLE
Buttons display problem

### ISSUE THREAD

**Issue by JaRutkowski** [jFeeSoft/office#2]
Buttons are quite not rosponsive - hidden when the window is smaller.

![image](https://user-images.githubusercontent.com/26207880/33229867-19201e92-d1d8-11e7-993f-df79b869e824.png)

![image](https://user-images.githubusercontent.com/26207880/33229871-319cc33a-d1d8-11e7-96bf-a873e14c2dad.png)

**Comment by twojcicki** [comment]
Ready.
