### ISSUE TITLE
Editing user organization data and role

### ISSUE THREAD

**Issue by JaRutkowski** [jFeeSoft/office#7]
There is an error (without console logs) while editing user organization data and role. It was checked on the earlier revision (commit: b397d747e974617f92e8b437ee46b20994daeaad) with the same effect.

![image](https://user-images.githubusercontent.com/26207880/33256550-c5fc5d9e-d352-11e7-84fd-a08ae8d85f2e.png)

**Comment by twojcicki** [comment]
Ready.
